### PR TITLE
update the default branch of the mycroft-skills repository

### PR DESCRIPTION
**Pull request by chrisveilleux**
#### Description
Fix a bug that defaults the skill branch to 20.08.  Latest is 21.02

#### Type of PR
If your PR fits more than one category, there is a high chance you should submit more than one PR. Please consider this carefully before opening the PR.
- [X] Bugfix
- [ ] Feature implementation
- [ ] Refactor of code (without functional changes)
- [ ] Documentation improvements
- [ ] Test improvements

#### Testing
More recent versions of skills are installed by MSM

#### Documentation
N/A

### CODE REVIEW

**Review by krisgesling — APPROVED** [review]
Good change - need to work out why the tests are failing. 

We also need to spend a bit of time in here to get everything updated and in sync with mycroft-core again.

**Comment by forslund** [comment]
Looks like the root cause for the issue is a behavior change in GitPython since the requrirement is not pinned.

**Comment by forslund** [comment]
I think we can merge this and fix the issue in a separate PR

**Comment by krisgesling** [comment]
Looks like #98 fixed it :+1:

**Pull request merged**
